#!/usr/bin/env python3
"""audit_quadrature.py — the independent check of the random-effect integral (pre-registration §7.4).

For every hierarchical member (M2H, M2S, M3H), at every heterogeneity grid value (0.5, 1, 2), the per-concept
joint log-likelihood of models.concept_scores is compared with a dense reference quadrature (80,001 points on
[-10 tau, 10 tau] in log space) at three kinds of parameters:
  (a) the generating parameters on data from the same member;
  (b) the FITTED parameters of the member on those data (the outer training fold, 52 concepts), scored on
      the held-out concepts — what the pipeline actually evaluates;
  (c) cross-fits: the member fitted to data generated by the other family's hierarchical member (M2H on M3H
      data and the reverse; M2S on M3H data), scored held-out — the awkward posteriors the procedure meets.
Reported per case: the max |error| over concepts, the max error's concept and its posterior SD/tau, and the
point-count ladder (TRAP_POINTS 64 -> 96 -> 128 with OUTER_POINTS at a third) so the §7.4 rule can be read off.
Pass at the production count (96): max |error| < 1e-3 nat in every (a)/(b) case; < 5e-3 nat in the cross-fits
(c) — there a mixture member fitted to heavy scale heterogeneity takes a very large slope, the likelihood in
the threshold shift becomes a staircase, and the trapezoid error converges only linearly; the bound on the
estimand is the case error / n_c per trial (5e-3 / 168 = 3e-5, a hundred times below the smallest declared
effect), stated in the pre-registration.
"""
from __future__ import annotations

import sys
import time

import numpy as np

import analyze as A
import models as M
import simulate as S
import jax
import jax.numpy as jnp

TOL = 1e-3
TOL_CROSS = 5e-3
LADDER = (64, 96, 128)
PROD = 96


def dense(name, theta, data: M.Trials, n_pts=80001, half=10.0):
    m = M.MEMBERS[name]
    tau = float(np.exp(theta[m.re_index]))
    u = np.linspace(-half * tau, half * tau, n_pts); du = u[1] - u[0]
    yy, kk, cc = jnp.asarray(data.y), jnp.asarray(data.k), jnp.asarray(data.cidx)
    fl = M.M3V_FLOOR_FRACTION * data.floor_sd
    th = jnp.asarray(theta)
    def one(uj):
        return jax.ops.segment_sum(m.loglik(th, yy, kk, uj, fl) * jnp.asarray(data.mask), cc, num_segments=data.n_concepts)
    ll_u = jax.lax.map(one, jnp.asarray(u), batch_size=2000)                                    # (U, C)
    logphi = -0.5 * (u / tau) ** 2 - np.log(tau) - 0.5 * np.log(2 * np.pi)
    return np.array(jax.scipy.special.logsumexp(ll_u + jnp.asarray(logphi)[:, None] + np.log(du), axis=0))


def compare(name, theta, data, label, ladder=LADDER):
    ref = dense(name, theta, data)
    chk = M.gh_node_check(name, theta, data, counts=ladder)
    errs = {n: np.abs(chk["scores"][n] - ref) for n in ladder}
    uh, sh = M.posterior_mode(name, theta, data)
    tau = float(np.exp(theta[M.MEMBERS[name].re_index]))
    worst = int(np.argmax(errs[PROD]))
    line = " ".join(f"P={n}: {errs[n].max():.1e}" for n in ladder)
    print(f"  {label:58s} {line}  worst concept {worst}: s_hat/tau {sh[worst] / tau:.2f}, u_hat/tau {uh[worst] / tau:+.2f}",
          flush=True)
    return errs[PROD].max()


def main():
    t0 = time.time()
    worst = 0.0
    worst_cross = 0.0
    cfg = A.Config()
    for name, key in (("M2H", "tau"), ("M2S", "omega"), ("M3H", "tau")):
        for val in (0.5, 1.0, 2.0):
            kw = {key: val}
            if name == "M3H":
                kw["sep"] = 2.0
            th = S.generator_theta(name, **kw)
            ds = S.make_dataset(name, th, n_per_family=8, D=4, layers=(41,), rho=0.0, seed=17)
            folds = A.stratified_folds(ds.family, 5, seed=1)
            train_c = np.setdiff1d(np.arange(ds.n_concepts), folds[0])
            train = A._subset(ds.y[:, 0], ds.k, ds.concept, train_c)
            test = A._subset(ds.y[:, 0], ds.k, ds.concept, folds[0], train.floor_sd)
            worst = max(worst, compare(name, th, test, f"(a) {name} {key}={val} generating theta, held-out"))
            r = M.fit(name, train, cfg.n_gh, cfg.n_starts, np.random.default_rng(3))
            worst = max(worst, compare(name, r.theta, test, f"(b) {name} {key}={val} fitted theta (conv {r.n_converged}/8)"))
            worst = max(worst, compare(name, r.theta, train, f"(b') {name} {key}={val} fitted theta, training set"))
    # (c) cross-fits
    for gen, gkw, fit_name in (("M3H", dict(tau=2.0, sep=2.0), "M2H"), ("M2H", dict(tau=2.0), "M3H"),
                               ("M3H", dict(tau=1.0, sep=0.5), "M2S"), ("M2S", dict(omega=2.0), "M3H"),
                               ("M2K", dict(alpha=3.0), "M2H"), ("M3L", dict(sep=1.0, pi0=0.2), "M2S")):
        th = S.generator_theta(gen, **gkw)
        ds = S.make_dataset(gen, th, n_per_family=8, D=4, layers=(41,), rho=0.0, seed=23)
        folds = A.stratified_folds(ds.family, 5, seed=1)
        train_c = np.setdiff1d(np.arange(ds.n_concepts), folds[0])
        train = A._subset(ds.y[:, 0], ds.k, ds.concept, train_c)
        test = A._subset(ds.y[:, 0], ds.k, ds.concept, folds[0], train.floor_sd)
        r = M.fit(fit_name, train, cfg.n_gh, cfg.n_starts, np.random.default_rng(5))
        worst_cross = max(worst_cross, compare(fit_name, r.theta, test, f"(c) {fit_name} fitted to {gen} {gkw} (conv {r.n_converged}/8)"))
    ok = worst < TOL and worst_cross < TOL_CROSS
    print(f"\nat P={PROD} (OUTER {M.OUTER_POINTS}): worst |error| generating/fitted {worst:.2e} nat (tolerance {TOL}), "
          f"cross-fits {worst_cross:.2e} nat (tolerance {TOL_CROSS}; bound on the estimand {worst_cross / 168:.1e} per trial) — "
          f"{'PASS' if ok else 'FAIL'}; {(time.time() - t0) / 60:.1f} min", flush=True)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
